// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/notebook.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNoteBookRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoteBookRequest) Reset()         { *m = GetNoteBookRequest{} }
func (m *GetNoteBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetNoteBookRequest) ProtoMessage()    {}
func (*GetNoteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_57e081d22210cac9, []int{0}
}
func (m *GetNoteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteBookRequest.Unmarshal(m, b)
}
func (m *GetNoteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteBookRequest.Marshal(b, m, deterministic)
}
func (dst *GetNoteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteBookRequest.Merge(dst, src)
}
func (m *GetNoteBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetNoteBookRequest.Size(m)
}
func (m *GetNoteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteBookRequest proto.InternalMessageInfo

func (m *GetNoteBookRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MsgNoteBook struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string   `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNoteBook) Reset()         { *m = MsgNoteBook{} }
func (m *MsgNoteBook) String() string { return proto.CompactTextString(m) }
func (*MsgNoteBook) ProtoMessage()    {}
func (*MsgNoteBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_57e081d22210cac9, []int{1}
}
func (m *MsgNoteBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNoteBook.Unmarshal(m, b)
}
func (m *MsgNoteBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNoteBook.Marshal(b, m, deterministic)
}
func (dst *MsgNoteBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNoteBook.Merge(dst, src)
}
func (m *MsgNoteBook) XXX_Size() int {
	return xxx_messageInfo_MsgNoteBook.Size(m)
}
func (m *MsgNoteBook) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNoteBook.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNoteBook proto.InternalMessageInfo

func (m *MsgNoteBook) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgNoteBook) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *MsgNoteBook) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MsgNoteBook) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgNoteBook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetNoteBookResponse struct {
	// repeated 修饰符表示字段是可变数组，即 slice 类型
	Data                 []*MsgNoteBook `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	User                 *MsgUser       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNoteBookResponse) Reset()         { *m = GetNoteBookResponse{} }
func (m *GetNoteBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetNoteBookResponse) ProtoMessage()    {}
func (*GetNoteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_57e081d22210cac9, []int{2}
}
func (m *GetNoteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteBookResponse.Unmarshal(m, b)
}
func (m *GetNoteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteBookResponse.Marshal(b, m, deterministic)
}
func (dst *GetNoteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteBookResponse.Merge(dst, src)
}
func (m *GetNoteBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetNoteBookResponse.Size(m)
}
func (m *GetNoteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteBookResponse proto.InternalMessageInfo

func (m *GetNoteBookResponse) GetData() []*MsgNoteBook {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetNoteBookResponse) GetUser() *MsgUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ErrorResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_57e081d22210cac9, []int{3}
}
func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (dst *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(dst, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNoteBookRequest)(nil), "notebook.GetNoteBookRequest")
	proto.RegisterType((*MsgNoteBook)(nil), "notebook.MsgNoteBook")
	proto.RegisterType((*GetNoteBookResponse)(nil), "notebook.GetNoteBookResponse")
	proto.RegisterType((*ErrorResponse)(nil), "notebook.ErrorResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotebookClient is the client API for Notebook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotebookClient interface {
	// rpc GetNotebookInfo (NotebookRequest) returns (NotebookResponse);
	GetNotebookInfo(ctx context.Context, in *GetNoteBookRequest, opts ...grpc.CallOption) (*GetNoteBookResponse, error)
}

type notebookClient struct {
	cc *grpc.ClientConn
}

func NewNotebookClient(cc *grpc.ClientConn) NotebookClient {
	return &notebookClient{cc}
}

func (c *notebookClient) GetNotebookInfo(ctx context.Context, in *GetNoteBookRequest, opts ...grpc.CallOption) (*GetNoteBookResponse, error) {
	out := new(GetNoteBookResponse)
	err := c.cc.Invoke(ctx, "/notebook.Notebook/GetNotebookInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotebookServer is the server API for Notebook service.
type NotebookServer interface {
	// rpc GetNotebookInfo (NotebookRequest) returns (NotebookResponse);
	GetNotebookInfo(context.Context, *GetNoteBookRequest) (*GetNoteBookResponse, error)
}

func RegisterNotebookServer(s *grpc.Server, srv NotebookServer) {
	s.RegisterService(&_Notebook_serviceDesc, srv)
}

func _Notebook_GetNotebookInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotebookServer).GetNotebookInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notebook.Notebook/GetNotebookInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotebookServer).GetNotebookInfo(ctx, req.(*GetNoteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notebook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notebook.Notebook",
	HandlerType: (*NotebookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotebookInfo",
			Handler:    _Notebook_GetNotebookInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notebook.proto",
}

func init() { proto.RegisterFile("proto/notebook.proto", fileDescriptor_notebook_57e081d22210cac9) }

var fileDescriptor_notebook_57e081d22210cac9 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0x9b, 0xfe, 0x71, 0x4a, 0x55, 0xc6, 0xaa, 0x4b, 0x51, 0xa8, 0x39, 0xd5, 0x83,
	0x15, 0xea, 0x37, 0x10, 0x44, 0x7a, 0x68, 0xc1, 0x80, 0x17, 0x2f, 0x92, 0x76, 0xd7, 0x10, 0x6a,
	0x32, 0x75, 0x77, 0x73, 0x10, 0xbf, 0xbc, 0xec, 0xec, 0xa6, 0x56, 0xc4, 0xdb, 0xfe, 0xe6, 0x3d,
	0x26, 0xef, 0x65, 0x60, 0xb8, 0xd5, 0x64, 0xe9, 0xb6, 0x24, 0xab, 0x56, 0x44, 0x9b, 0x29, 0x23,
	0xf6, 0x6a, 0x1e, 0x1d, 0x7b, 0xbd, 0x32, 0x4a, 0x7b, 0x2d, 0xbe, 0x01, 0x7c, 0x54, 0x76, 0x49,
	0x56, 0xdd, 0x13, 0x6d, 0x12, 0xf5, 0x51, 0x29, 0x63, 0xf1, 0x1c, 0xba, 0xce, 0xf3, 0x9a, 0x4b,
	0xd1, 0x18, 0x37, 0x26, 0x07, 0x49, 0xc7, 0xe1, 0x5c, 0xc6, 0x5f, 0xd0, 0x5f, 0x98, 0xac, 0xb6,
	0xe3, 0x10, 0xda, 0x36, 0xb7, 0xef, 0x2a, 0xb8, 0x3c, 0xa0, 0x80, 0xae, 0xa9, 0x8a, 0x22, 0xd5,
	0x9f, 0xa2, 0xc9, 0xf3, 0x1a, 0x9d, 0x3f, 0x2f, 0xd2, 0x4c, 0x89, 0x96, 0xf7, 0x33, 0xe0, 0x19,
	0x84, 0xf5, 0x22, 0xda, 0xff, 0x18, 0x1e, 0x42, 0x33, 0x97, 0xa2, 0xcd, 0xb3, 0x66, 0x2e, 0xe3,
	0x35, 0x9c, 0xfc, 0xca, 0x6a, 0xb6, 0x54, 0x1a, 0x85, 0xd7, 0x10, 0xc9, 0xd4, 0xa6, 0xa2, 0x31,
	0x6e, 0x4d, 0xfa, 0xb3, 0xd3, 0xe9, 0xae, 0xfd, 0x5e, 0xd2, 0x84, 0x2d, 0x78, 0x05, 0x91, 0xdb,
	0xcd, 0xb1, 0xfa, 0xb3, 0xc1, 0x94, 0x7f, 0xc4, 0xc2, 0x64, 0xcf, 0x46, 0xe9, 0x84, 0xa5, 0xf8,
	0x09, 0x06, 0x0f, 0x5a, 0x93, 0xde, 0xad, 0x47, 0x88, 0xd6, 0x24, 0xeb, 0x8a, 0xfc, 0x76, 0x0d,
	0x0b, 0x65, 0x8c, 0x6b, 0x12, 0x1a, 0x06, 0x74, 0x6e, 0x0e, 0xe3, 0x0b, 0xf2, 0x7b, 0xf6, 0x02,
	0xbd, 0x65, 0xc8, 0x84, 0x4b, 0x38, 0x0a, 0x1d, 0x1c, 0xce, 0xcb, 0x37, 0xc2, 0x8b, 0x9f, 0xc4,
	0x7f, 0x4f, 0x31, 0xba, 0xfc, 0x47, 0xf5, 0xe9, 0x56, 0x1d, 0x3e, 0xe3, 0xdd, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x17, 0xdc, 0xef, 0x96, 0xfa, 0x01, 0x00, 0x00,
}
