version: "3"

services:
  srv-api:
#    build:
#      context: .
#      dockerfile: api/Dockerfile
    image: golang:1.10
    working_dir: /go/src/kuaibiji
    command: ["go", "run", "api/api.go"]
    volumes:
      - .:/go/src/kuaibiji
    links:
      - consul
    depends_on:
      - consul
      - microhq-micro
    ports:
      - 8880:8080
      - 8881:8081
      - 8882:8082
    environment:
      # 设置地址
#      MICRO_SERVER_ADDRESS: 8500
      MICRO_REGISTRY_ADDRESS: consul:8500
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  microhq-micro:
    image: microhq/micro
    ports:
      - 8080:8080
#    command: api --handler=rpc
    command: api
    environment:
      MICRO_REGISTRY_ADDRESS: consul:8500
    depends_on:
      - consul
  microhq-sidecar:
    image: microhq/micro
    ports:
      - 8081:8081
#    command: api --handler=rpc --namespace=gua
    command: proxy
    environment:
      MICRO_REGISTRY_ADDRESS: consul:8500
    depends_on:
      - consul
  redis:
    ports:
      - "6385:6379"
    image: "redis:alpine"
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
