version: "3"

services:
  srv-greeter:
    build:
      context: .
      dockerfile: services/go/srv-greeter/Dockerfile
#    build:
#      .
    volumes:
      - .:/go/src/kuaibiji
#    ports:
#      - 50051:50051
    links:
      - consul
    depends_on:
      - consul
      - mysql
      - redis
#      - microhq-micro
#    ports:
#      - 8082:8080
    environment:
      MICRO_REGISTRY_ADDRESS: consul:8500