# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class UserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserInfo = channel.unary_unary(
        '/user.User/GetUserInfo',
        request_serializer=proto_dot_user__pb2.GetUserRequest.SerializeToString,
        response_deserializer=proto_dot_user__pb2.GetUserResponse.FromString,
        )
    self.Login = channel.unary_unary(
        '/user.User/Login',
        request_serializer=proto_dot_user__pb2.LoginRequest.SerializeToString,
        response_deserializer=proto_dot_user__pb2.LoginResponse.FromString,
        )
    self.Logout = channel.unary_unary(
        '/user.User/Logout',
        request_serializer=proto_dot_user__pb2.LogoutRequest.SerializeToString,
        response_deserializer=proto_dot_user__pb2.LogoutResponse.FromString,
        )


class UserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=proto_dot_user__pb2.GetUserRequest.FromString,
          response_serializer=proto_dot_user__pb2.GetUserResponse.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=proto_dot_user__pb2.LoginRequest.FromString,
          response_serializer=proto_dot_user__pb2.LoginResponse.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=proto_dot_user__pb2.LogoutRequest.FromString,
          response_serializer=proto_dot_user__pb2.LogoutResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
