# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import weixin_pb2 as proto_dot_weixin__pb2


class WeixinStub(object):
  """repeated 修饰符表示字段是可变数组，即 slice 类型
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WeixinLogin = channel.unary_unary(
        '/weixin.Weixin/WeixinLogin',
        request_serializer=proto_dot_weixin__pb2.RequestWeixinLogin.SerializeToString,
        response_deserializer=proto_dot_weixin__pb2.ResponseWeixinLogin.FromString,
        )
    self.WeixinLogout = channel.unary_unary(
        '/weixin.Weixin/WeixinLogout',
        request_serializer=proto_dot_weixin__pb2.RequestWeixinLogout.SerializeToString,
        response_deserializer=proto_dot_weixin__pb2.ResponseWeixinLogout.FromString,
        )


class WeixinServicer(object):
  """repeated 修饰符表示字段是可变数组，即 slice 类型
  """

  def WeixinLogin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WeixinLogout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WeixinServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WeixinLogin': grpc.unary_unary_rpc_method_handler(
          servicer.WeixinLogin,
          request_deserializer=proto_dot_weixin__pb2.RequestWeixinLogin.FromString,
          response_serializer=proto_dot_weixin__pb2.ResponseWeixinLogin.SerializeToString,
      ),
      'WeixinLogout': grpc.unary_unary_rpc_method_handler(
          servicer.WeixinLogout,
          request_deserializer=proto_dot_weixin__pb2.RequestWeixinLogout.FromString,
          response_serializer=proto_dot_weixin__pb2.ResponseWeixinLogout.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'weixin.Weixin', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
