# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/weixin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/weixin.proto',
  package='weixin',
  syntax='proto3',
  serialized_pb=_b('\n\x12proto/weixin.proto\x12\x06weixin\"X\n\x12RequestWeixinLogin\x12\r\n\x05\x61ppid\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\x12\x0f\n\x07js_code\x18\x03 \x01(\t\x12\x12\n\ngrant_type\x18\x04 \x01(\t\"K\n\x13ResponseWeixinLogin\x12\x0e\n\x06openid\x18\x01 \x01(\t\x12\x13\n\x0bsession_key\x18\x02 \x01(\t\x12\x0f\n\x07unionid\x18\x03 \x01(\t\"%\n\x13RequestWeixinLogout\x12\x0e\n\x06userId\x18\x01 \x01(\t\"$\n\x14ResponseWeixinLogout\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x9b\x01\n\x06Weixin\x12\x46\n\x0bWeixinLogin\x12\x1a.weixin.RequestWeixinLogin\x1a\x1b.weixin.ResponseWeixinLogin\x12I\n\x0cWeixinLogout\x12\x1b.weixin.RequestWeixinLogout\x1a\x1c.weixin.ResponseWeixinLogoutb\x06proto3')
)




_REQUESTWEIXINLOGIN = _descriptor.Descriptor(
  name='RequestWeixinLogin',
  full_name='weixin.RequestWeixinLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='weixin.RequestWeixinLogin.appid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret', full_name='weixin.RequestWeixinLogin.secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='js_code', full_name='weixin.RequestWeixinLogin.js_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grant_type', full_name='weixin.RequestWeixinLogin.grant_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=118,
)


_RESPONSEWEIXINLOGIN = _descriptor.Descriptor(
  name='ResponseWeixinLogin',
  full_name='weixin.ResponseWeixinLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='openid', full_name='weixin.ResponseWeixinLogin.openid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='weixin.ResponseWeixinLogin.session_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unionid', full_name='weixin.ResponseWeixinLogin.unionid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=195,
)


_REQUESTWEIXINLOGOUT = _descriptor.Descriptor(
  name='RequestWeixinLogout',
  full_name='weixin.RequestWeixinLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='weixin.RequestWeixinLogout.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=234,
)


_RESPONSEWEIXINLOGOUT = _descriptor.Descriptor(
  name='ResponseWeixinLogout',
  full_name='weixin.ResponseWeixinLogout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='weixin.ResponseWeixinLogout.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=272,
)

DESCRIPTOR.message_types_by_name['RequestWeixinLogin'] = _REQUESTWEIXINLOGIN
DESCRIPTOR.message_types_by_name['ResponseWeixinLogin'] = _RESPONSEWEIXINLOGIN
DESCRIPTOR.message_types_by_name['RequestWeixinLogout'] = _REQUESTWEIXINLOGOUT
DESCRIPTOR.message_types_by_name['ResponseWeixinLogout'] = _RESPONSEWEIXINLOGOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestWeixinLogin = _reflection.GeneratedProtocolMessageType('RequestWeixinLogin', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTWEIXINLOGIN,
  __module__ = 'proto.weixin_pb2'
  # @@protoc_insertion_point(class_scope:weixin.RequestWeixinLogin)
  ))
_sym_db.RegisterMessage(RequestWeixinLogin)

ResponseWeixinLogin = _reflection.GeneratedProtocolMessageType('ResponseWeixinLogin', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEWEIXINLOGIN,
  __module__ = 'proto.weixin_pb2'
  # @@protoc_insertion_point(class_scope:weixin.ResponseWeixinLogin)
  ))
_sym_db.RegisterMessage(ResponseWeixinLogin)

RequestWeixinLogout = _reflection.GeneratedProtocolMessageType('RequestWeixinLogout', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTWEIXINLOGOUT,
  __module__ = 'proto.weixin_pb2'
  # @@protoc_insertion_point(class_scope:weixin.RequestWeixinLogout)
  ))
_sym_db.RegisterMessage(RequestWeixinLogout)

ResponseWeixinLogout = _reflection.GeneratedProtocolMessageType('ResponseWeixinLogout', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEWEIXINLOGOUT,
  __module__ = 'proto.weixin_pb2'
  # @@protoc_insertion_point(class_scope:weixin.ResponseWeixinLogout)
  ))
_sym_db.RegisterMessage(ResponseWeixinLogout)



_WEIXIN = _descriptor.ServiceDescriptor(
  name='Weixin',
  full_name='weixin.Weixin',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=275,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='WeixinLogin',
    full_name='weixin.Weixin.WeixinLogin',
    index=0,
    containing_service=None,
    input_type=_REQUESTWEIXINLOGIN,
    output_type=_RESPONSEWEIXINLOGIN,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WeixinLogout',
    full_name='weixin.Weixin.WeixinLogout',
    index=1,
    containing_service=None,
    input_type=_REQUESTWEIXINLOGOUT,
    output_type=_RESPONSEWEIXINLOGOUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEIXIN)

DESCRIPTOR.services_by_name['Weixin'] = _WEIXIN

# @@protoc_insertion_point(module_scope)
