version: "3"
services:
  web:
    build: .
#    entrypoint: ./cmd/serve all
#    command: go install -ldflags="-s -w"  /root/go/src/kuaibiji/cmd/serve/all.go
    ports:
      - "8004:8004"
    links:
      - jaeger
      - consul
    working_dir:
      - /data/www/services/serverice_code
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

