# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/api.proto',
  package='api',
  syntax='proto3',
  serialized_pb=_b('\n\x0fproto/api.proto\x12\x03\x61pi\"\x1c\n\x0cIndexRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rIndexResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t25\n\x03\x41pi\x12.\n\x05Index\x12\x11.api.IndexRequest\x1a\x12.api.IndexResponseb\x06proto3')
)




_INDEXREQUEST = _descriptor.Descriptor(
  name='IndexRequest',
  full_name='api.IndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='api.IndexRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_INDEXRESPONSE = _descriptor.Descriptor(
  name='IndexResponse',
  full_name='api.IndexResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='api.IndexResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['IndexRequest'] = _INDEXREQUEST
DESCRIPTOR.message_types_by_name['IndexResponse'] = _INDEXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IndexRequest = _reflection.GeneratedProtocolMessageType('IndexRequest', (_message.Message,), dict(
  DESCRIPTOR = _INDEXREQUEST,
  __module__ = 'proto.api_pb2'
  # @@protoc_insertion_point(class_scope:api.IndexRequest)
  ))
_sym_db.RegisterMessage(IndexRequest)

IndexResponse = _reflection.GeneratedProtocolMessageType('IndexResponse', (_message.Message,), dict(
  DESCRIPTOR = _INDEXRESPONSE,
  __module__ = 'proto.api_pb2'
  # @@protoc_insertion_point(class_scope:api.IndexResponse)
  ))
_sym_db.RegisterMessage(IndexResponse)



_API = _descriptor.ServiceDescriptor(
  name='Api',
  full_name='api.Api',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=85,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='Index',
    full_name='api.Api.Index',
    index=0,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_INDEXRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['Api'] = _API

# @@protoc_insertion_point(module_scope)
