"""empty message

Revision ID: 8e6fd67296db
Revises: 34f3be73b6c7
Create Date: 2016-09-30 01:04:58.652658

"""

# revision identifiers, used by Alembic.
revision = '8e6fd67296db'
down_revision = '34f3be73b6c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogcomments', sa.Column('replys', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogcomments', 'replys')
    ### end Alembic commands ###
