# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class UserStub(object):
  """service 定义开放调用的服务，即 NotebookService 微服务
  rpc 定义服务内的 GetNotebookInfo 远程调用
  方法名  方法参数                 返回值
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserInfo = channel.unary_unary(
        '/user.User/GetUserInfo',
        request_serializer=proto_dot_user__pb2.GetUserRequest.SerializeToString,
        response_deserializer=proto_dot_user__pb2.GetUserResponse.FromString,
        )


class UserServicer(object):
  """service 定义开放调用的服务，即 NotebookService 微服务
  rpc 定义服务内的 GetNotebookInfo 远程调用
  方法名  方法参数                 返回值
  """

  def GetUserInfo(self, request, context):
    """rpc GetNotebookInfo (NotebookRequest) returns (NotebookResponse);
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=proto_dot_user__pb2.GetUserRequest.FromString,
          response_serializer=proto_dot_user__pb2.GetUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
