// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8576c801f264bfab, []int{0}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MsgUser struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UpdateTime           string   `protobuf:"bytes,2,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUser) Reset()         { *m = MsgUser{} }
func (m *MsgUser) String() string { return proto.CompactTextString(m) }
func (*MsgUser) ProtoMessage()    {}
func (*MsgUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8576c801f264bfab, []int{1}
}
func (m *MsgUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUser.Unmarshal(m, b)
}
func (m *MsgUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUser.Marshal(b, m, deterministic)
}
func (dst *MsgUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUser.Merge(dst, src)
}
func (m *MsgUser) XXX_Size() int {
	return xxx_messageInfo_MsgUser.Size(m)
}
func (m *MsgUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUser.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUser proto.InternalMessageInfo

func (m *MsgUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgUser) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *MsgUser) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MsgUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type GetUserResponse struct {
	// repeated 修饰符表示字段是可变数组，即 slice 类型
	Data                 *MsgUser `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8576c801f264bfab, []int{2}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetData() *MsgUser {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*MsgUser)(nil), "user.MsgUser")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// rpc GetNotebookInfo (NotebookRequest) returns (NotebookResponse);
	GetUserInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.User/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// rpc GetNotebookInfo (NotebookRequest) returns (NotebookResponse);
	GetUserInfo(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_user_8576c801f264bfab) }

var fileDescriptor_user_8576c801f264bfab = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x0d, 0x2e,
	0x3e, 0xf7, 0xd4, 0x92, 0xd0, 0xe2, 0xd4, 0xa2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x31, 0x2e, 0x36, 0x90, 0x8c, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0xa7,
	0x54, 0xcb, 0xc5, 0xee, 0x5b, 0x9c, 0x0e, 0x52, 0x89, 0x4b, 0x89, 0x90, 0x1c, 0x17, 0x57, 0x69,
	0x41, 0x4a, 0x62, 0x49, 0x6a, 0x48, 0x66, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x0e, 0x49, 0x04, 0x24,
	0x9f, 0x5c, 0x94, 0x0a, 0x93, 0x67, 0x86, 0xc8, 0x23, 0x44, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0x26,
	0xf9, 0x25, 0xe6, 0xa6, 0x4a, 0xb0, 0x80, 0x65, 0xe1, 0x7c, 0x25, 0x13, 0x2e, 0x7e, 0xb8, 0x43,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x14, 0xb9, 0x58, 0x52, 0x12, 0x4b, 0x12, 0xc1, 0x8e,
	0xe0, 0x36, 0xe2, 0xd5, 0x03, 0x7b, 0x0e, 0xea, 0xc6, 0x20, 0xb0, 0x94, 0x91, 0x13, 0x17, 0x0b,
	0xd8, 0xc5, 0x56, 0x5c, 0xdc, 0x50, 0xdd, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x22, 0x10, 0xb5, 0xa8,
	0x3e, 0x97, 0x12, 0x45, 0x13, 0x85, 0x58, 0x93, 0xc4, 0x06, 0x0e, 0x2f, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0xdf, 0xad, 0xa6, 0x43, 0x01, 0x00, 0x00,
}
