// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/notebook/proto/notebook.proto

package notebook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message 对应生成代码的 struct
// 定义客户端请求的数据格式
type NotebookRequest struct {
	// [修饰符] 类型 字段名 = 标识符;
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotebookRequest) Reset()         { *m = NotebookRequest{} }
func (m *NotebookRequest) String() string { return proto.CompactTextString(m) }
func (*NotebookRequest) ProtoMessage()    {}
func (*NotebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_36d757dad1c2d432, []int{0}
}
func (m *NotebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotebookRequest.Unmarshal(m, b)
}
func (m *NotebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotebookRequest.Marshal(b, m, deterministic)
}
func (dst *NotebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotebookRequest.Merge(dst, src)
}
func (m *NotebookRequest) XXX_Size() int {
	return xxx_messageInfo_NotebookRequest.Size(m)
}
func (m *NotebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotebookRequest proto.InternalMessageInfo

func (m *NotebookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 定义服务端响应的数据格式
type NotebookResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Title                []string `protobuf:"bytes,4,rep,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotebookResponse) Reset()         { *m = NotebookResponse{} }
func (m *NotebookResponse) String() string { return proto.CompactTextString(m) }
func (*NotebookResponse) ProtoMessage()    {}
func (*NotebookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notebook_36d757dad1c2d432, []int{1}
}
func (m *NotebookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotebookResponse.Unmarshal(m, b)
}
func (m *NotebookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotebookResponse.Marshal(b, m, deterministic)
}
func (dst *NotebookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotebookResponse.Merge(dst, src)
}
func (m *NotebookResponse) XXX_Size() int {
	return xxx_messageInfo_NotebookResponse.Size(m)
}
func (m *NotebookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotebookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotebookResponse proto.InternalMessageInfo

func (m *NotebookResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotebookResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotebookResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *NotebookResponse) GetTitle() []string {
	if m != nil {
		return m.Title
	}
	return nil
}

func init() {
	proto.RegisterType((*NotebookRequest)(nil), "notebook.NotebookRequest")
	proto.RegisterType((*NotebookResponse)(nil), "notebook.NotebookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotebookClient is the client API for Notebook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotebookClient interface {
	// rpc 定义服务内的 GetNotebookInfo 远程调用
	GetNotebookInfo(ctx context.Context, in *NotebookRequest, opts ...grpc.CallOption) (*NotebookResponse, error)
}

type notebookClient struct {
	cc *grpc.ClientConn
}

func NewNotebookClient(cc *grpc.ClientConn) NotebookClient {
	return &notebookClient{cc}
}

func (c *notebookClient) GetNotebookInfo(ctx context.Context, in *NotebookRequest, opts ...grpc.CallOption) (*NotebookResponse, error) {
	out := new(NotebookResponse)
	err := c.cc.Invoke(ctx, "/notebook.Notebook/GetNotebookInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotebookServer is the server API for Notebook service.
type NotebookServer interface {
	// rpc 定义服务内的 GetNotebookInfo 远程调用
	GetNotebookInfo(context.Context, *NotebookRequest) (*NotebookResponse, error)
}

func RegisterNotebookServer(s *grpc.Server, srv NotebookServer) {
	s.RegisterService(&_Notebook_serviceDesc, srv)
}

func _Notebook_GetNotebookInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotebookServer).GetNotebookInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notebook.Notebook/GetNotebookInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotebookServer).GetNotebookInfo(ctx, req.(*NotebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notebook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notebook.Notebook",
	HandlerType: (*NotebookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotebookInfo",
			Handler:    _Notebook_GetNotebookInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/notebook/proto/notebook.proto",
}

func init() {
	proto.RegisterFile("services/notebook/proto/notebook.proto", fileDescriptor_notebook_36d757dad1c2d432)
}

var fileDescriptor_notebook_36d757dad1c2d432 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0xcf, 0xcb, 0x2f, 0x49, 0x4d, 0xca, 0xcf, 0xcf, 0xd6, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0x87, 0x73, 0xf5, 0xc0, 0x5c, 0x21, 0x0e, 0x18, 0x5f, 0x49, 0x95, 0x8b, 0xdf,
	0x0f, 0xca, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xe2, 0xb8, 0x04, 0x10, 0xca,
	0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0xc0, 0xaa, 0x58, 0x83,
	0x98, 0x32, 0x53, 0xe0, 0xfa, 0x98, 0x10, 0xfa, 0x84, 0x04, 0xb8, 0x98, 0x13, 0xd3, 0x53, 0x25,
	0x98, 0xc1, 0x8a, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92, 0x9c, 0x54, 0x09, 0x16,
	0x05, 0x66, 0x0d, 0xce, 0x20, 0x08, 0xc7, 0x28, 0x8c, 0x8b, 0x03, 0x66, 0xbe, 0x90, 0x17, 0x17,
	0xbf, 0x7b, 0x6a, 0x09, 0x8c, 0xeb, 0x99, 0x97, 0x96, 0x2f, 0x24, 0xa9, 0x07, 0xf7, 0x00, 0x9a,
	0x6b, 0xa5, 0xa4, 0xb0, 0x49, 0x41, 0x5c, 0xa8, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0xaf, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0xc6, 0xb8, 0xf7, 0x19, 0x01, 0x00, 0x00,
}
